AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to create an Amazon RDS MySQL instance using the Free 
  Tier instance type with configurable networking and security options.

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: "Select the VPC for the RDS instance."
    # Allows user to select the VPC where the RDS instance will be deployed.

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Select the subnet(s) for the RDS instance."
    # Specifies a list of subnets where the RDS instance will be placed.
    # RDS instances require subnets across at least two Availability Zones for high availability.

  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    AllowedValues:
      - db.t4g.micro
    Description: "Free Tier instance class for the RDS instance."
    # Restricts the instance type to Free Tier-eligible db.t4g.micro.

  AllocatedStorage:
    Type: Number
    Default: 20
    Description: "Storage size in GB for the database."
    # Sets the storage capacity for the RDS instance. 20GB is typical for Free Tier use.

  DBName:
    Type: String
    Default: usernameDB
    Description: "Name of the MySQL database."
    # Defines the database name that will be created on the RDS instance.

  MasterUsername:
    Type: String
    Default: admin
    Description: "Master username for the MySQL database."
    # Sets the administrator username for accessing the database.

  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: "Password for the master username."
    # Sets the password for the administrator username, masked with NoEcho for security.

  DBParameterGroupName:
    Type: String
    Default: default.mysql8.0
    Description: "RDS parameter group for MySQL."
    # Specifies a parameter group for MySQL engine configurations.

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "Security group(s) for the RDS instance."
    # Allows the user to select security groups to control network access to the RDS instance.

Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS MySQL instance."
      SubnetIds: !Ref SubnetIds
      DBSubnetGroupName: "p3-username-dbsubnetgroup"  
    # Replace "username" with your username.
    # Creates a DB subnet group using the selected subnets for RDS.
    # Required for RDS instances that span multiple Availability Zones for resilience.

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      DBName: !Ref DBName
      Engine: "mysql"
      EngineVersion: "8.0.39"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      VPCSecurityGroups: !Ref SecurityGroupIds
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroupName
      MultiAZ: false
      PubliclyAccessible: false
    # Defines the RDS MySQL instance with specified settings:
    # - DBInstanceClass and AllocatedStorage set the instance type and storage size.
    # - DBName, MasterUsername, and MasterUserPassword set up the MySQL database and login credentials.
    # - VPCSecurityGroups and DBSubnetGroupName control network and availability settings.
    # - PubliclyAccessible is set to false, limiting access within the VPC.

Outputs:
  RDSInstanceEndpoint:
    Description: "Connection endpoint for the RDS MySQL instance."
    Value: !GetAtt MyRDSInstance.Endpoint.Address
    # Outputs the endpoint URL to connect to the RDS instance.

  RDSInstancePort:
    Description: "Port number for the RDS MySQL instance."
    Value: !GetAtt MyRDSInstance.Endpoint.Port
    # Outputs the port number, typically 3306 for MySQL.
